inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 4.2
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

ClassLength:
  Enabled: false

# 基本80までで120超は禁止のイメージ
Metrics/LineLength:
  Max: 120

# デフォルトの10では厳しいので緩和
Metrics/MethodLength:
  Max: 20

# ラムダをパラメータにした際に違反とみなされるRuboCopの不具合を回避するため
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'app/models/task.rb'
