- hosts: site
  become: true
  user: vagrant
  pre_tasks:
    - name: Yum update
      yum: name=* state=latest

    - name: policycoreutils-pythonをインストール
      yum: 
        name: policycoreutils-python
        state: latest

    - name: SELinuxを無効化
      selinux: state=disabled
  roles:
    - firewall
    - git
    - docker-engine
    - { role: certbot,           when: stage == 'production' }
    - { role: dummy_certificate, when: stage == 'staging' }
    - containers
    - { role: hosts,             when: stage == 'staging' }
    - { role: rbenv,             when: stage == 'staging' }
    - { role: envirionments,     when: stage == 'staging' }
    - { role: phantomjs,         when: stage == 'staging' }
    - { role: fonts,             when: stage == 'staging' }
  tasks:
    - name: SELinuxの有効化
      selinux: state=enforcing policy=targeted

