- name: DBコンテナのIPアドレス取得
  shell: |
    {% raw %}
    docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db
    {% endraw %}
  register: db_ip_address
  changed_when: False

- name: /etc/hostsファイルを配置
  template:
    src: hosts.j2
    dest: /etc/hosts
