default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: stack_space_development
  timeout: 5000
  url: <%= ENV['DATABASE_URL_DEVELOPMENT'] %>

test:
  <<: *default
  database: stack_space_test
  timeout: 10000
  url: <%= ENV['DATABASE_URL_TEST'] %>

production:
  <<: *default
  database: stack_space_production
  timeout: 5000
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
